#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
    @Time : 2022/3/20 16:54
    @Author  : jack.li
    @Site    : 
    @File    : baidu_search.py

"""
import random
from urllib.request import quote
import json
import requests

user_agent = [
	"Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)",
	"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; AcooBrowser; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
	"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Acoo Browser; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506)",
	"Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.35; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
	"Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)",
	"Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727; Media Center PC 6.0)",
	"Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)",
	"Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.2; .NET CLR 3.0.04506.30)",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.3 (Change: 287 c9dfb30)",
	"Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3) Arora/0.6",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1",
	"Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0",
	"Mozilla/5.0 (X11; Linux i686; U;) Gecko/20070322 Kazehakase/0.4.5",
	"Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Fedora/1.9.0.8-1.fc10 Kazehakase/0.5.6",
	"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20",
	"Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; fr) Presto/2.9.168 Version/11.52"
]

HEADER = {
'User-Agent': random.choice(user_agent),  # 浏览器头部
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', # 客户端能够接收的内容类型
'Accept-Language': 'en-US,en;q=0.5', # 浏览器可接受的语言
'Connection': 'keep-alive', # 表示是否需要持久连接
}

path = "D:\\investee.json"

with open(path, "r") as f:
    data = f.read()

data = json.loads(data)

data_list = [(k, v) for k, v in data.items()]
data_list.sort(key=lambda x: x[1], reverse=True)
iv = 0
for k, v in data_list:
    print(iv, k, v)
    iv += 1

d = {
    "鼎晖": "北京鼎晖创新投资顾问有限公司",
    "中国国有企业结构调整基金": "中国国有企业结构调整基金股份有限公司",
    "EDBI": "",
    "Lightspeed Venture Partners美国光速": "Lightspeed Venture Partners",
    "图灵创投": "北京图灵正时投资管理有限公司",
    "凯辉创新基金": "Cathay Innovation",
    "Greenoaks Capital": "Greenoaks Capital",
    "NEA恩颐投资": "New Enterprise Associates",
    "张江科投": "上海张江科技创业投资有限公司",
    "青樾基金": "青岛青樾云科股权投资管理企业（有限合伙）",
    "沃赋资本": "宁波沃赋投资管理有限公司",
    "Translink Capital": "Translink Capital",
    "Mirae Asset": "Mirae Asset Financial Group",
    "中关村协同创新基金": "北京中关村协同创新投资基金管理有限公司",
    "美的资本": "美的创业投资管理有限公司",
    "普洛斯GLP": "普洛斯投资（上海）有限公司",
    "鼎晖资本": "鼎暉資本基金管理有限公司",
    "临芯资本": "上海临丰投资合伙企业（有限合伙）",
    "Spark Capital": "Spark Capital",
    "蔻图资本": "Coatue Management",
    "Kleiner Perkins Caufield & Byers ": "Kleiner Perkins Caufield & Byers(KPCB全球)",
    "A16Z": "Andreessen Horowitz",
    "绝了基金": "广州绝了股权投资基金管理有限公司",
    "XVC创投": "宁波梅山保税港区艾克思创新投资管理有限公司",
    "PAG": "Penske Automotive Group, Inc.",
    "涌铧资本": "上海涌铧投资管理有限公司",
    "头头是道基金": "杭州头头是道投资合伙企业（有限合伙）",
    "温氏资本": "广东温氏投资有限公司",
    "云悦资本": "云悦投资顾问（深圳）有限公司",
    "中银粤财": "中银粤财股权投资基金管理（广东）有限公司",
    "上海人工智能产业投资基金": "上海人工智能产业投资管理中心（有限合伙）",
    "宝捷会创新消费基金": "宁波钟鼎宝捷会创业投资中心（有限合伙）",
    "海纳亚洲创投基金SIG": "root",
    "国药中金": "国药中金（上海）私募股权投资管理有限公司",
    "上海人工智能产业基金": "上海人工智能产业股权投资基金合伙企业（有限合伙）",
    "海创汇": "海创汇科技创业发展有限公司",
    "eWTP科技创新基金": "阿里巴巴（中国）有限公司",
    "老虎环球": "老虎环球基金(Tiger Global Management) ",
    "熠美投资": "上海熠美私募基金管理合伙企业（有限合伙）",
    "淡马锡Temasek": "root",
    "中关村前沿基金": "北京中关村发展前沿企业投资基金（有限合伙）",
    "中金文化消费基金": "中金文化消费产业股权投资基金（厦门）合伙企业（有限合伙）",
    "Infinity Venture Partners": {"name": "Infinity Venture Partners", "desc": "Infinity Venture Partners（IVP）成立于2009年，目前管理的三期基金共数亿美金规模。 公司是一家专注投资大中华地区TMT行业的早期基金，关注领域包括消费升级、企业服务、文化娱乐、医疗健康、泛高科技等。 在北京、台北和东京设有办公室，同时也是e.ventures基金联盟在亚洲的分支及机构，具备独特的海外资源，着力于帮助被投资企业走出中国，在国际市场上崭露头角。 IVP的团队由成功创业者和经验丰富的投资者共同组成，海外基金出资人包括美国、欧洲以及日本的上市公司、FOF基金、家族基金等。  "},
    "红杉中国基金": "root",
    "泽羽资本": "宁波梅山保税港区泽羽投资合伙企业（有限合伙）",
    "联想集团": "root",
    "中网投": "中国互联网投资基金管理有限公司",
    "巢生资本": "杭州巢生投资管理有限公司",
    "郑志刚C资本": "北京新雅博瑞文化发展有限公司",
    "TF Capital泰福资本": "上海泰甫创业投资管理有限公司",
    "3W Fund": "3W Fund Management Limited",
    "APlus Partners": "APlus Partners Star Investment Limited",
    "Salesforce": "Salesforce.Com, Inc.",
    "宽带资本CBC": "北京天地融创创业投资有限公司",
    "全明星基金": "全明星投资All-Stars Investment",
    "Lone Pine Capital": {"name": "Lone Pine Capital", "desc": "Lone Pine Capital于1997年由Tiger Management的常务董事兼分析师Steven Mandel创立，为期7年。根据2006年12月4日发行的Barron's报道，曼德尔现在管理着80亿美元，自他基金成立以来每年返回超过25％。  "},
    "青岛国信": {"name": "青岛国信发展（集团）有限责任公司", "desc": ""},
    "合肥产投": {"name": "合肥市产业投资控股（集团）有限公司", "desc": ""},
    "龙柏资本": {"name": "深圳市龙柏资本投资管理有限公司", "desc": ""},
    "维梧资本Vivo Capital": {"name": "维梧资本Vivo Capital", "desc": "维梧资本（Vivo Capital）成立于1996年，是一家专注于生命科学和健康领域的投资公司。维梧资本管理着超过17亿美元的基金，目前通过其7.5亿美元的第8期基金在中美两个市场投资有潜力的生物技术和生命科学企业。  "},
    "Partech Ventures": {"name": "Partech Ventures", "desc": "Partech Ventures成立于1982年，主要投资于美国和欧洲地区的技术创新型公司，如互联网消费和信息技术行业。  "},
    "夏尔巴": {"name": "四川夏尔巴户外运动有限公司", "desc": ""},
    "中关村启航基金": {"name": "北京中关村发展启航产业投资基金（有限合伙）", "desc": ""},
    "安达富基金": {"name": "富安達基金管理有限公司", "desc": ""},
    "祥峰投资中国基金": {"name": "祥恩股权投资管理（上海）有限公司", "desc": ""},
    "华夏桃李资本": {"name": "北京华夏桃李咨询有限公司", "desc": ""},
    "景旭创投": {"name": "上海景旭创业投资有限公司", "desc": ""},
    "王兴": "not valid",
    "LYFE Capital": {"name": "洲岭私募基金管理（上海）有限公司", "desc": ""},
    "国方母基金": {"name": "上海国方私募基金管理有限公司", "desc": ""},
    "德迅": {"name": "深圳市德迅投资有限公司", "desc": ""},
    "国开装备基金": {"name": "国开熔华产业投资基金管理有限责任公司", "desc": ""},
    "联通中金": {"name": "联通中金私募股权投资管理（深圳）有限公司", "desc": ""},
    "高盛集团": {"name": "高盛集团（Goldman Sachs）", "desc": "高盛集团（Goldman Sachs）成立于1869年，是全世界历史最悠久及规模最大的投资银行之一，总部位于纽约，并在东京、伦敦和香港设有分部，在23个国家拥有41个办事处。向全球提供广泛的投资、咨询和金融服务，拥有大量的多行业客户，包括私营公司，金融企业，政府机构以及个人。高盛集团目前有四大类业务：投资银行、机构客户服务、投资与借贷、投资管理。  "},
    "上海科创投集团": {"name": "上海科技创业投资（集团）有限公司", "desc": ""},
    "Fidelity Management and Research Company ": {"name": "Fidelity Management and Research Company ", "desc": "富达管理研究公司是一家私人投资管理机构。Fidelity Management & Research Company is a privately owned investment manager.  "},
    "国调基金/结构调整基金": {"name": "中国国有企业结构调整基金股份有限公司", "desc": ""},
    "GBA大湾区基金": {"name": "大湾区共同家园投资有限公司(Greater Bay Area Homeland Investments Limited)", "desc": ""},
    "通衡浙商资本": {"name": "杭州通衡浙商投资管理有限公司", "desc": ""},
    "创享欢聚": {"name": "创享欢聚投资（上海）有限公司", "desc": ""},
    "红杉种子基金": {"name": "红杉资本股权投资管理（天津）有限公司", "desc": ""},
    "新潮集团": {"name": "江苏新潮创新投资集团有限公司", "desc": ""},
    "华润国调厦门消费基金": {"name": "华润国调（厦门）私募基金管理有限公司", "desc": ""},
    "小米产业基金": {"name": "湖北小米长江产业投资基金管理有限公司", "desc": ""},
    "国泰财富基金": {"name": "xxxx", "desc": ""},
    "北拓资本": {"name": "北京联创北拓投资控股股份有限公司", "desc": ""},
    "极值资本": {"name": "极值（上海）咨询管理有限公司", "desc": ""},
    "合享资本": {"name": "广东合享投资管理有限公司", "desc": ""},
    "尚承资本": {"name": "上海嘉寻资产管理合伙企业（有限合伙）", "desc": ""},
    "Morgan Stanley摩根士丹利": {"name": "Morgan Stanley摩根士丹", "desc": "Morgan Stanley摩根士丹利成立于1935年，是一家全球领先的国际性金融服务公司，业务范围涵盖投资银行、证券、投资管理以及财富管理。  "},
    "TPG软银合资基金": {"name": "xxxx", "desc": ""},
    "黑石集团": {"name": "黑石集团Blackstone", "desc": "黑石集团Blackstone是全世界最大的独立另类资产管理机构之一，也是一家金融咨询服务机构。该公司1985年成立，2007年6月在纽交易上市（NYSE：BX）。"},
    "L catterton": {"name": "L Catterton", "desc": "L Catterton由成立于2001年的LVMH集团旗下L Capital 和成立于1989年的美国私募股权公司Catterton合并而来，基金品牌沉淀了超30年的专注于消费行业的投资经验。目前，L Catterton在消费各个领域进行了超过200项投资，总管理规模280亿美金（约合人民币近1800亿元）。L Catterton专注于全球消费行业新兴期、成长期以及成熟期的投资，重点关注食品饮料、大健康、宠物、时尚、餐饮、零售、个人护理、美妆、奢侈品、医疗服务、消费科技等赛道。 "},
    "上汽恒旭资本": {"name": "上海上汽恒旭投资管理有限公司", "desc": ""},
    "腾讯产业生态投资": {"name": "深圳市腾讯计算机系统有限公司", "desc": ""},
    "科银资本Collinstar Capital": {"name": "科银资本Collinstar Capital", "desc": "科银资本由区块链领域知名投资人“火星人”Ryan发起并创立，科银资本聚焦于金融科技区块链、数字货币领域的投资，先后投资过早期的比特币、以太坊等数字货币，也布局过区块链基础建设、云计算中心等重资产项目。  "},
    "君茂资本": {"name": "烟台君茂资产管理有限公司", "desc": ""},
    "恩然创投": {"name": "南京恩然瑞光投资管理中心（有限合伙）", "desc": ""},
    "致君水滴": {"name": "嘉兴致君水滴资产管理有限公司", "desc": ""},
    "光速资本": {"name": "光速中国创业投资基金", "desc": "光速中国创业投资基金是一家专注于中国市场的创业投资基金，覆盖早期和成长期，聚焦绿色科技、硬科技、企业服务、医疗科技和消费领域，管理着30亿美元的资金，在上海、北京、香港设有办公室。"},
    "网聚资本": {"name": "深圳网聚投资有限责任公司", "desc": ""},
    "冲盈资本": {"name": "途觅咨询（北京）有限公司", "desc": ""},
    "超越摩尔": {"name": "上海超越摩尔股权投资基金合伙企业（有限合伙）", "desc": ""},
    "英诺天使": {"name": "天津英诺创业投资合伙企业（有限合伙）", "desc": ""},
    "富达投资Fidelity Investments": {"name": "美国富达投资集团", "desc": "Fidelity Investment Group 成立于1964年，是一家综合性的金融服务机构。  "},
    "源合资本": {"name": "北京思源合一企业管理咨询合伙企业（有限合伙）", "desc": ""},
    "铭耀资本": {"name": "上海铭耀股权投资管理有限公司", "desc": ""},
    "起点资本": {"name": "广州起点投资有限公司", "desc": ""},
    "MindWorks Ventures概念资本": {"name": "深圳概念智品科技发展有限公司", "desc": ""},
    "中小企业发展基金": {"name": "xxxx", "desc": ""},
    "十维资本":  {"name": "杭州鸣弦投资管理有限公司", "desc": ""},
    "大湾区共同家园投资有限公司": {"name": "大湾区共同家园投资有限公司", "desc": ""},
    "博世": {"name": "博世（中国）投资有限公司", "desc": ""},
    "深创": {"name": "xxx", "desc": ""},
    "北洋海棠基金": {"name": "天津北洋海棠创业投资管理有限公司", "desc": ""},
    "软银愿景二号基金": {"name": "软银", "desc": ""},
    "中金启德": {"name": "中金启德（厦门）创新生物医药股权投资基金合伙企业（有限合伙）", "desc": ""},
    "厚朴基金": {"name": "xxxx", "desc": "厚朴基金酝酿于2003年，2007年水到渠成。这家在海外设立、专注于中国的私人股权投资基金，管理资金规模为25亿美元，完全以国际标准的合伙制模式打造，其投资者全部为世界排名前三位的机构投资者，包括主权财富基金、新加坡淡马锡投资。 厚朴投资管理公司对于市场的影响力主要来自其三位创始合伙人：高盛高华证券公司董事长方风雷、原毕马威会计师事务所中国及香港业务主席何潮辉和原高盛亚洲投资银行部联席主管王忠信。投资方向均与中国概念相关，一是直接投资中国企业，二是协助中国企业海外投资，三是协助海外企业投资中国。  "},
    "易方达资本": {"name": "易方达基金管理有限公司", "desc": ""},
    "深圳中小担": {"name": "", "desc": ""},
    "欧游集团": {"name": "", "desc": ""},
    "Shasta Ventures": {"name": "Shasta Ventures", "desc": "Shasta Ventures成立于2004年，是一家专注于信息科技和互联网领域的早期投资机构。管理着超过 10 亿美元的资金，重点是 SaaS、网络安全、基础设施、数据智能和相机视觉等领域的早期企业初创公司。  "},
    "黑藻资本": {"name": "上海黑藻信息科技合伙企业（有限合伙）", "desc": ""},
    "IFC国际金融公司": {"name": "国际金融公司，简称IFC(International Financial Corporation)，成立于1956年，总部设在华盛顿，属世界银行集团。是专门向经济不发达会员国的私营企业提供贷款和投资的国际性金融组织。  ", "desc": ""},
    "阿布扎比资本集团": {"name": "阿布扎比财团", "desc": "阿布扎比财团是依托阿联酋最大的酋长国——阿布扎比酋长国王室，所成立的跨国投资集团，是该国皇家财富基金ADIA(阿布扎比投资局)的一部分，据称总资产为5千亿英镑，根据牛津商务集团的报告，该财团是仅次于日本银行的世界第二大财团。"},
    "高盛资产管理旗下基金": {"name": "高盛集团（Goldman Sachs）", "desc": "高盛集团（Goldman Sachs）成立于1869年，是全世界历史最悠久及规模最大的投资银行之一，总部位于纽约，并在东京、伦敦和香港设有分部，在23个国家拥有41个办事处。向全球提供广泛的投资、咨询和金融服务，拥有大量的多行业客户，包括私营公司，金融企业，政府机构以及个人。高盛集团目前有四大类业务：投资银行、机构客户服务、投资与借贷、投资管理。  "},
    "易凯基金": {"name": "易凯明天（北京）投资顾问有限公司", "desc": ""},
    "新加坡政府投资公司": {"name": "GIC新加坡政府投资公司", "desc": "GIC新加坡政府投资公司是一家来自新加坡的主权投资基金，其主要任务是管理新加坡的外汇储备，跨出新加坡国界向海外大举投资，目前管理的资产超过千亿美元。  "},
    "Temasek": {"name": "Temasek淡马锡", "desc": "淡马锡成立于1974年，是一家设立在新加坡的投资公司。淡马锡的投资着眼于四大主题：转型中的经济体、增长中的中产阶级、强化中的比较优势和新兴的龙头企业。兰亭投资是淡马锡的独资子公司。  "},
    "如川资本": {"name": "厦门如川投资管理有限公司", "desc": ""},
    "新势能基金": {"name": "深圳梅岭高能股权投资管理有限公司", "desc": ""},
    "Balderton Capital": {"name": "Balderton Capital", "desc": "Balderton Capital成立于2000年，是一家欧洲最大的风险投资机构之一。主要投资于早期阶段。Balderton 的成立是为了支持欧洲最雄心勃勃的技术企业家。公司通过 Balderton Growth I 在早期和成长阶段投资于欧洲成立的公司。Balderton Capital已经在欧洲扎根 20 多年，开发了无与伦比的本地洞察力，并支持处于从早期阶段到退出的各个增长阶段的公司。公司在伦敦、巴黎、柏林和斯德哥尔摩等主要枢纽拥有 20 多名投资者。  "},
    "挚金资本": {"name": "深圳挚金资本投资管理有限公司", "desc": ""},
    "GGV 纪源资本": {"name": "纪源投资咨询（上海）有限公司", "desc": ""},
    "浙商创新资本": {"name": "浙江浙商创新资本管理有限公司", "desc": ""},
    "李静": {"name": "xxx", "desc": ""},
    "Eurazeo": {"name": "欧瑞泽（上海）投资管理有限公司", "desc": ""},
    "Techstars Ventures": {"name": "Techstars Ventures", "desc": "Techstars Ventures 成立于2012年，之前被称为Bullet Time Ventures，是一家风险投资机构，旗下管理超过1亿5000万美元基金。  "},
    "复星实业": {"name": "上海复星实业有限公司", "desc": ""},
    "三一创新": {"name": "三一创新（北京）投资管理有限公司", "desc": ""},
    "中移创新产业基金": {"name": "中移国投创新投资管理有限公司", "desc": ""},
    "招商致远": {"name": "招商致远资本投资有限公司", "desc": ""},
    "华人文化产业基金": {"name": "华人文化产业投资基金", "desc": ""},
    "超越摩尔基金": {"name": "上海超越摩尔股权投资基金合伙企业（有限合伙）", "desc": ""},
    "中青旅红奇基金": {"name": "中青旅红奇（横琴）基金管理有限公司", "desc": ""},
    "三正健康": {"name": "南京建邺三正厚德投资管理有限公司", "desc": ""},
    "方和资本": {"name": "北京雅宝方和投资管理有限责任公司", "desc": ""},
    "赛富": {"name": "x", "desc": ""},
    "李康林": {"name": "xxx", "desc": ""},
    "Iconiq Capital": {"name": "Iconiq Capital", "desc": "ICONIQ Capital是一家全球性运作公司，是独立的美国证券交易委员会注册的投资顾问  "},
    "一旗力合": {"name": "一旗力合汽车新技术创业投资（南京）有限公司", "desc": ""},
    "AME Cloud Ventures": {"name": "AME Cloud Ventures", "desc": "AME Cloud Ventures是一家风险投资机构，主要投资于围绕数据的底层及价值链提供服务的科技公司，投资阶段涵盖种子期到成熟期阶段。  "},
    "小米产投": {"name": "湖北小米长江产业投资基金管理有限公司", "desc": ""},
    "日本软银集团": {"name": "软银", "desc": ""},
    "大华创投": {"name": "优欧弼投资管理（上海）有限公司", "desc": ""},
    "中信证券投资有限公司": {"name": "中信证券投资有限公司", "desc": ""},
    "Lightspeed": {"name": "Lightspeed India Partners", "desc": "自2004年以来，Lightspeed Venture Partners已投资于印度直接和跨境公司，Lightspeed Venture Partners has invested in direct and cross-border Indian companies since 2004, and has an Indian advisory team with offices in New Delhi and Bengaluru. They invest across several stages and sectors in India, including technology-led businesses as well as non-technology opportunities in sectors such as advertising and media, business services, financial services, healthcare, education and retail.Their principal goal is to provide talented entrepreneurs and their teams with growth or early-stage capital, coupled with ongoing consulting and advising to help them disrupt and transform large markets in the domestic economy.  "},
    "国投创业投资管理有限公司": {"name": "国投创业投资管理有限公司", "desc": ""},
    "绿洲资本Vitalbridge": {"name": "上海象洲投资管理有限公司", "desc": ""},
    "青赢创投": {"name": "深圳前海青赢创业投资合伙企业（有限合伙）", "desc": ""},
    "炼金术资本": {"name": "深圳炼金术投资基金管理有限公司", "desc": ""},
    "复朴资本": {"name": "湖北复朴创业投资管理有限责任公司", "desc": ""},
    "WI Harper Group": {"name": "中经合集团", "desc": "中经合集团成立于1993年，是一家专注于早期和扩张期企业的风险投资公司。管理逾7.5亿美元的基金，已投资近百家企业。"},
    "孙正义": {"name": "xx", "desc": ""},
    "Dragoneer": {"name": "Dragoneer Investment Group（DIG）", "desc": "Dragoneer Investment Group总部在旧金山，是一家长期的、以增长为导向的公共与私人投资机构。  "},
    "湖畔山南资本": {"name": "杭州湖畔山南资本管理有限公司", "desc": ""},
    "甲骨文": {"name": "Oracle Corporation", "desc": "甲骨文公司，全称甲骨文股份有限公司(甲骨文软件系统有限公司)，是全球最大的企业级软件公司，总部位于美国加利福尼亚州的红木滩。1989年正式进入中国市场。2013年，甲骨文已超越 IBM ，成为继 Microsoft 后全球第二大软件公司。  "},
    "云曦一号基金": {"name": "杭州云曦一号股权投资合伙企业（有限合伙）", "desc": ""},
    "Matrix Partners经纬海外": {"name": "Matrix Partners", "desc": "Matrix Partners是一家专注于种子和早期投资的风险投资公司。  "},
    "密码资本": {"name": "北京密码网安信息咨询有限公司", "desc": ""},
    "两江基金": {"name": "重庆两江股权投资基金管理有限公司", "desc": ""},
    "中科创": {"name": "中科创金融控股集团有限公司", "desc": ""},
    "凯雷亚洲基金": {"name": "凱雷亞洲基金投資控股有限公司", "desc": ""},
    "个人": {"name": "xx", "desc": ""},
    "eGarden ventures": {"name": "Egarden Ventures Hong Kong Ltd.", "desc": "毅园投资是香港一家主要从事投资控股的公司。"},
    "南京市创新投资集团": {"name": "南京市创新投资集团有限责任公司", "desc": ""},
    "易凯未来产业基金": {"name": "天津易凯明天资产管理有限公司", "desc": ""},
    "凯珩资本": {"name": "上海凯珩投资管理有限公司", "desc": ""},
    "同程众创启程金禾基金": {"name": "苏州启程金禾创业投资合伙企业（有限合伙）", "desc": ""},
    "丰川资本": {"name": "北京丰川弘瑞私募基金管理有限公司", "desc": ""},
    "泛大西洋投资集团": {"name": "General Atlantic泛大西洋投资", "desc": "General Atlantic泛大西洋投资成立于1980年，是一家知名的私人股权投资基金之一。  "},
    "寇图资本": {"name": "Coatue Management", "desc": "Coatue Management是纽约一家由对冲基金投资人发起成立的一间私企投资公司，主要专注投资于公共市场技术，媒体和电信行业。投资的市场覆盖全球，涉猎偏向多媒体传播，现代技术产业方面，以及电信电讯市场和其下归属组织。"},
    "网易公司": {"name": "x", "desc": ""},
    "五源资本-": {"name": "x", "desc": ""},
    "点石资本": {"name": "深圳市点石投资管理有限公司", "desc": ""},
    "芯动能投资": {"name": "北京芯动能投资管理有限公司", "desc": ""},
    "中华开发": {"name": "中华开发工银", "desc": "中华开发工业银行是台湾最大的直接投资机构，亦为亚洲最大的投资机构之一，由60余位菁英所组成的专业投资团队，除了拥有50余年广泛而深入的产业投资经验外，所投资的逾300家企业客户多已成功地将营运触角以台湾为核心，逐步发展至大中华地区，进而延伸至全球各大主要市场。而透过客户所布建绵密的产业国际网络，建构了中华开发工银完整产业价值链下之投资组合，以及阶段性投资策略下逐步的发展蓝图。  "},
    "赛富投资": {"name": "赛富投资管理咨询（上海）有限公司", "desc": ""},
    "鼎珮集团": {"name": "鼎珮投資集團（香港）有限公司", "desc": ""},
    "贝恩资本BainCapital": {"name": "", "desc": ""},
    "一苇资本": {"name": "英赛瑞博企业管理咨询（北京）有限公司", "desc": ""},
    "瑞士再保险集团": {"name": "瑞士再保险公司", "desc": "瑞士再保险公司是瑞士最大的专业再保险公司，仅次于慕尼黑再保险公司的第二大国际再保险公司。"},
    "五岳资本N5Capital": {"name": "北京五岳天下投资咨询有限公司", "desc": ""},
    "歌路资本": {"name": "歌路承铭企业咨询（北京）有限公司", "desc": ""},
    "Tiger老虎基金-中国": {"name": "Tiger Global Management", "desc": "Tiger Global Management，LLC是一家在全球部署资本的投资公司。 Tiger Global寻求长期为投资者赢得优越的风险调整回报。该公司的基本导向投资主要集中在全球互联网，技术，电信，媒体消费和工业部门。私募股权战略具有十年的投资期限，面向增长型私营公司。公众股权的努力强调对个别公司的深度尽职调查和长期的世俗主题。 作为一家企业，Tiger Global重视诚信，智慧诚信，持续改进，过程优于结果，团队合作，成为世界一流企业和长期思考。 Tiger Global Management，LLC成立于2001年3月1日，总部位于纽约，在香港，新加坡，班加罗尔和墨尔本设有分支机构。  "},
    "泽盛创投": {"name": "广东泽盛股权投资合伙企业（有限合伙）", "desc": ""},
    "张晓高": {"name": "x", "desc": ""},
    "王江": {"name": "x", "desc": ""},
    "Dragonfly Capital": {"name": "Dragonfly Capital", "desc": "总部位于旧金山的Dragonfly Capital"},
    "致远资本": {"name": "北京致远融悦咨询有限公司", "desc": ""},
    "普超资本": {"name": "杭州普超投资管理有限公司", "desc": ""},
    "未来启创基金": {"name": "北京未来启创基金管理有限公司", "desc": ""},
    "德迅资本": {"name": "深圳市德迅投资有限公司", "desc": ""},
    "渤溢基金": {"name": "重庆渤溢股权投资基金管理有限公司", "desc": ""},
    "中关村发展前沿基金": {"name": "北京中发前沿投资管理有限公司", "desc": ""},
    "海纳亚洲创投基金": {"name": "SIG海纳亚洲创投基金", "desc": "SIG海纳亚洲创投基金是海纳国际集团 (SIG)的全资子公司，是总部设于美国的全球领先的量化交易金融公司，特别关注中国互联网、消费类、服务类、以及数字媒体方面的企业，投资处于各发展阶段的企业。15余年来，聚焦中国互联网、消费等相关领域，已经投资了包括：字节跳动、声网、博纳影业、薄荷健康、翼鸥教育、云智慧、乡村基、大麦网、Finch、闪送、Musical.ly、伴鱼、PatPat、拉面说、松鼠Ai、天天拍车、英雄体育、威马汽车、喜马拉雅、晶泰科技、雅乐科技、一条、云学堂、智云健康、最右等在内的超过350家公司，总投资金额超过35亿美金，其中70多家公司已经通过上市或者并购实现退出。"},
    "超限": {"name":"xxxx", "desc": ""},
    "建信股权": {"name":"建信股权投资管理有限责任公司", "desc": ""},
    "建兴医疗基金": {"name":"北京建兴医疗健康产业股权投资合伙企业（有限合伙）", "desc": ""},
    "温氏国际": {"name":"溫氏國際集團有限公司", "desc": ""},
    "Data Collective": {"name": "Data Collective" ,"desc": "Data Collective是加利福尼亚州旧金山的一家风险投资公司，拥有一支由经验丰富的风险资本家、技术企业家和执业工程师组成的独特团队，主要在种子期和早期构建大数据、深度计算和IT基础设施公司中进行投资。"},
    "上海生物医药基金": {"name":"上海生物医药产业股权投资基金管理有限公司", "desc": ""},
    "Star VC": {"name":"Star Ventures", "desc": "Star Ventures是一家风险投资公司。 Founded in 1992 as one of the first Venture Funds in Israel with $1B under management STAR has successfully built over 180 category leading technology companies. STAR has orchestrated over 75 successful IPOs and M&As to date. These include companies such as Acopia, Alvarion, BigBand, Broadbus, Ciena, Creo, Identify, Orckit, Precise, Sheer Networks and Topio.  "},
    "UpHonest Capital": {"name":"UpHonest Capital", "desc": "UpHonest Capital是专注跨境早期投资，致力于发掘中美两地最具成长性的、创新性的创业企业年轻、全球化背景的管理团队。"},
    "三花弘道": {"name":"杭州三花弘道创业投资合伙企业（有限合伙）", "desc": ""},
    "科源产业基金": {"name":"宁波科源投资管理合伙企业（有限合伙）", "desc": ""},
    "棕榈资本": {"name":"溫氏國際集團有限公司", "desc": ""},
    "东方弘泰资本": {"name":"云卓弘泰资本投资有限公司", "desc": ""},
    "中金传化基金": {"name":"宁波鄞州区水易企业管理合伙企业（有限合伙）", "desc": ""},
    "刘峻": {"name":"xx", "desc": ""},
    "Lavender Hill Capital Partners": {"name":"Lavender Hill Capital Partners", "desc": "Lavender Hill Capital Partners是一家香港投资公司。  "},
    "国寿科创基金": {"name":"国寿资本投资有限公司", "desc": ""},
    "红衫资本": {"name":"x", "desc": ""},
    "Vivo Capital": {"name":"Vivo Capital（维梧资本）成立于1996年，致力于在中美投资和建立生命科学和医疗健康领域的高品质企业。维梧管理着超过十亿美金的基金，通过独特的多角度的投资策略发现并投资有潜力的公司。在美国，维梧投资公司的创新医疗产品均处于晚期研发或上市阶段。在大中华地区则倾向于投资已进入成长阶段的生命科学和医疗健康产业公司。维梧在美国加州帕洛阿尔托，中国上海、北京、和成都设有办事处。  ", "desc": ""},
    "中银投": {"name":"中银投资有限公司", "desc": ""},
    "某知名投资机构": {"name":"xx", "desc": ""},
    "一汽集团": {"name":"中国第一汽车集团有限公司", "desc": ""},
    "招商启航资本": {"name":"深圳招商启航投资管理有限公司", "desc": ""},
    "华胥基金": {"name":"华胥基金管理（广州）有限公司", "desc": ""},
    "阿里巴巴公益基金会": {"name":"阿里巴巴公益基金会", "desc": "为规范发展公益事业，阿里巴巴集团及旗下子公司联合成立的“阿里巴巴公益基金会”已于2012年通过国家民政部批准审核批准，马云成为该基金会第一号志愿者。"},
    "马云公益基金会": {"name":"浙江马云公益基金会", "desc": "浙江马云公益基金会”于2014年12月15日正式成立，是马云先生个人出资在国内设立的非公募基金会。"},
    "安大略省教师退休基金": {"name":"安大略省教師退休金計劃（亞洲）有限公司", "desc": "安大略省教师退休金计划（亚洲）有限公司，成立于2012-10-10，法定代表人为SARAH JANE ROWE，经营状态为仍注册  "},
    "清源创投": {"name":"深圳力合创业投资有限公司", "desc": ""},
    "上海拙朴投资": {"name":"上海拙朴投资管理中心（有限合伙）", "desc": ""},
    "勘柏资本": {"name":"上海勘柏资产管理有限公司", "desc": ""},
    "甲子启航": {"name":"深圳甲子启航投资有限公司", "desc": ""},
    "变量资本": {"name":"宁波变量致玺投资管理合伙企业（有限合伙）", "desc": ""},
    "Aspex": {"name":"Aspex Management", "desc": "Aspex Management是一家投资管理公司，专注于泛亚股票投资。  "},
    "中信产业基金CPE源峰基金": {"name":"中信产业投资基金管理有限公司", "desc": ""},
    "Greenoaks Capital Management": {"name":"Greenoaks Capital Management", "desc": "Greenoaks Capital Management 是一家有英国背景的风险投资机构，主要投资于与创新和技术相关的组合。  "},
    "中美绿色基金": {"name":"中美绿色基金管理有限公司", "desc": ""},
    "红杉海外": {"name":"x", "desc": ""},
    "U.S. Venture Partners": {"name":"US Venture Partners 成立于1981年，是一家主要投资于早期阶段的风险投资机构，投资领域涵盖数字传播、网络系统、消费与商业服务、媒介、半导体、清洁能源、医疗健康、生物科技等。 ", "desc": ""},
    "WinX Capital凯乘资本": {"name":"上海氢遇见氧企业管理有限公司", "desc": ""},
    "Digital Currency Group": {"name":"Digital Currency Group", "desc": "DCG总部位于纽约市，是数字货币行业的活跃种子投资者，在30多个国家/地区拥有100多项投资。"},
    "深圳前海母基金": {"name":"前海母基金股权投资（深圳）有限公司", "desc": ""},
    "中金资本旗下": {"name":"中金资本运营有限公司", "desc": ""},
    "凯辉能源基金": {"name":"湖北凯辉智慧新能源基金合伙企业（有限合伙）", "desc": ""},
    "正轩资本": {"name":"深圳市正轩投资有限公司", "desc": ""},
    "合力资本": {"name":"合力資本有限公司", "desc": ""},
    "元和资本": {"name":"北京伟豪元和资本投资管理中心（有限合伙）", "desc": ""},
    "华业天成资本": {"name":"深圳华业天成投资有限公司", "desc": ""},
    "红点创投 中国基金": {"name":"红点风险投资（Redpoint Ventures）", "desc": "红点风险投资（Redpoint Ventures），红点投资主要专注于企业级软件、通讯基础设施、存储和数据中心、社交网络、移动互联网等方向的投资，目前共计管理资金34亿美元，在全球已累计投资382家公司，其中121家上市或被并购,是一家领导性的风险投资公司，专门投资给具有领导和改变行业潜力的创新型公司。目前，该公司主要投资在企业软件、通讯基础设施、移动和无线，存储和数据中心架构以及管理。红点投资主要专注于企业级软件、通讯基础设施、存储和数据中心、社交网络、移动互联网等方向的投资，目前共计管理资金34亿美元，在全球已累计投资382家公司，其中121家上市或被并购。  "},
    "朗姿韩亚": {"name":"北京朗姿韩亚资产管理有限公司", "desc": ""},
    "Tiger老虎基金": {"name": "Tiger Global Management", "desc": "Tiger Global Management，LLC是一家在全球部署资本的投资公司。 Tiger Global寻求长期为投资者赢得优越的风险调整回报。该公司的基本导向投资主要集中在全球互联网，技术，电信，媒体消费和工业部门。私募股权战略具有十年的投资期限，面向增长型私营公司。公众股权的努力强调对个别公司的深度尽职调查和长期的世俗主题。 作为一家企业，Tiger Global重视诚信，智慧诚信，持续改进，过程优于结果，团队合作，成为世界一流企业和长期思考。 Tiger Global Management，LLC成立于2001年3月1日，总部位于纽约，在香港，新加坡，班加罗尔和墨尔本设有分支机构。  "},
    "云锋": {"name":"x", "desc": ""},
    "赛曼基金": {"name":"广东赛曼投资有限公司", "desc": ""},
    "DST Global Solutions": {"name":"DST Global", "desc": "DST Global是一家总部位于俄罗斯的风险投资机构，投资方向定在互联网市场，专注于物联网、人工智能、区块链、3D打印、纳米机器人等。"},
    "Intel Capital": {"name":"英特尔投资", "desc": "英特尔投资是英特尔公司下设的事业部门，在全球范围内向创新型科技公司进行资本投资。"},
    "混沌投资": {"name":"上海混沌投资（集团）有限公司", "desc": ""},
    "商汤国香资本": {"name":"溫氏國際集團有限公司", "desc": ""},
    "五源资本-晨兴资本": {"name":"x", "desc": ""},
    "金沙江联合": {"name":"x", "desc": ""},
    "创新工场智赋成长基金": {"name":"北京互联创新工场投资管理有限公司", "desc": ""},
    "CPE源峰资本": {"name":"中信产业投资基金管理有限公司", "desc": ""},
    "腾讯双百": {"name":"xxxx", "desc": ""},
    "Tenaya Capital": {"name":"Tenaya Capital", "desc": "Tenaya Capital 成立于2009年，是一家投资于成长阶段的风险投资机构，主要投资领域包括软件，互联网消费，通信，半导体，电子和清洁技术。  "},
    "北京量子跃动科技有限公司": {"name":"北京量子跃动科技有限公司", "desc": ""},
    "罡漩资本": {"name":"上海罡漩企业管理咨询合伙企业（有限合伙）", "desc": ""},
    "远识资本": {"name":"北京博衍灏海管理咨询有限公司", "desc": ""},
    "阳光融汇": {"name":"阳光融汇资本投资管理有限公司", "desc": ""},
    "中汇金": {"name":"上海中汇金投资集团股份有限公司", "desc": ""},
    "果睿资本": {"name":"上海果睿投资管理有限公司", "desc": ""},
    "兰璞创投": {"name":"上海兰璞投资管理合伙企业（普通合伙）", "desc": ""},
    "BAI）": {"name":"x", "desc": ""},
    "赞思餐饮": {"name":"上海赞思餐饮管理有限公司", "desc": ""},
    "创瑞投资": {"name":"上海创瑞投资管理有限公司", "desc": ""},
    "Paradox": {"name":"Paradox, Inc.", "desc": "Paradox是一家人力资源对话式AI平台，Paradox提供了一个对话式AI平台，使人力资源和人才团队能够自动执行管理任务，并提供实时的候选人和员工沟通。Paradox与许多世界领先的招聘和人才管理系统进行了协作集成。  "},
    "Pavilion Capital": {"name":"兰亭投资Pavilion Capital", "desc": "兰亭投资Pavilion Capital是一家专注于私募股权投资的新加坡投资机构。  "},
    "Benchmark Capital": {"name":"Benchmark Capital", "desc": "Benchmark Capital是一家初创企业投资公司，关注打破多种行业壁垒的社会、移动、本地和云企业。"},
    "Shata Capital": {"name":"Shata Capital", "desc": "Shata Capital由Gobi Partners的前合伙人Don Jiang创建。Shata Capital，专注于为用户开发区块链项目。"},
    "Neumann": {"name":"Neumann Advisors", "desc": "Neumann Advisors是成立于2016年的对冲基金管理公司，管理资产数亿美元。公司由扎根中国多年的资深科技投资人士在香港创建，聚焦科技投资，秉赋价值投资信念，目标为投资者创造长期优秀回报。  "},
    "招商清控": {"name":"青岛招商清控私募股权投资基金管理有限公司", "desc": ""},
    "老股东": {"name":"xx", "desc": ""},
    "ABI资本": {"name":"元实投资咨询（深圳）有限公司", "desc": ""},
    "窄门集团": {"name": "北京窄门信息技术有限公司", "desc": ""},
    "灵均投资": {"name": "宁波灵均投资管理合伙企业（有限合伙）", "desc": ""},
    "NewView Capital": {"name": "NewView Capital", "desc": "NewView Capital推出一个新的风险投资模式，以推动企业家，风险投资公司和有限合伙人在这个不断变化的企业中实现可持续增长。  "},
    "厦门半导体": {"name": "厦门半导体投资集团有限公司", "desc": ""},
    "璞米": {"name": "璞米投资咨询（中国）有限公司", "desc": ""},
    "Guinness Asset Management": {"name": "Guinness Asset Management", "desc": "Guinness Asset 主要专注于投资管理，向个人和机构投资者提供一系列仅长期有效管理的基金。吉尼斯（Guinness）成立于2003年，是独立机构，由员工全资拥有。  "},
    "光济资本": {"name": "宁波光谦企业管理咨询有限公司", "desc": "dead"},
    "Adams Street Partners": {"name": "Adams Street Partners", "desc": "Adams Street Partners是一家自1972年以来一直投资的私募股权投资者。他们目前管理着超过200亿美元。"},
    "全国社保基金": {"name": "x", "desc": ""},
    "某战略投资方": {"name": "x", "desc": ""},
    "汉桥资本": {"name": "SinoVest Capital", "desc": "SinoVest Capital于2009年在新加坡成立为资产管理公司。主要业务是为新加坡，中国大陆和香港的认可家庭财富和机构投资者提供财富管理服务。"},
    "微木资本": {"name": "微木智业投资（北京）有限公司", "desc": ""},
    "保利资本科技基金": {"name": "保利（横琴）资本管理有限公司", "desc": ""},
    "晶凯资本": {"name": "上海晶凯投资有限公司", "desc": ""},
    "星元创新资本": {"name": "北京星元创新股权投资基金管理有限公司", "desc": ""},
    "宝富投资": {"name": "烟台宝富投资中心（有限合伙）", "desc": ""},
    "汇鼎资本": {"name": "汇鼎资本管理有限公司", "desc": ""},
    "MPM Capital": {"name": "MPM Capital", "desc": "MPM Capital通过种子，早期和后期风险投资以及私募股权投资迎合医疗行业。  "},
    "国新国同": {"name": "国新国同（杭州）投资管理有限公司", "desc": ""},
    "中科海创": {"name": "xxx", "desc": ""},
    "沧海资本": {"name": "北京沧海普华管理咨询有限公司", "desc": ""},
    "博世中国": {"name": "博世（中国）投资有限公司", "desc": ""},
    "Kleiner Perkins": {"name": "Kleiner Perkins Caufield & Byers(KPCB全球)", "desc": "Kleiner Perkins Caufield & Byers/KPCB是一家硅谷风险投资公司，关注信息技术、生命科学、绿色科技领域。他们是许多重要公司的早期投资者，包括亚马逊，美国在线，康柏，艺电，谷歌，Intuit，Macromedia，Netscape，Segway和Sun Microsystems。  "},
    "信达汉石": {"name": "宁波信达汉石投资管理有限公司", "desc": ""},
    "屹唐长厚": {"name": "北京屹唐长厚创业投资基金管理有限公司", "desc": ""},
    "哇牛资本": {"name": "苏州工业园区哇牛投资有限公司", "desc": ""},
    "优势资本": {"name": "优势金控（上海）资产管理有限公司", "desc": ""},
    "长润资本": {"name": "深圳长润资产管理有限公司", "desc": ""},
    "Paradigm": {"name": "AJG Systems Inc.", "desc": "Paradigm是一家加密货币机构级交易通讯平台，为机构交易者在聊天中自动进行场外交易。"},
    "Upfront Ventures": {"name": "Upfront Ventures", "desc": "Upfront Ventures于 1996 年在洛杉矶成立，是一家专注于早期技术公司的风险投资公司。"},
    "九轩资本": {"name": "上海九轩投资管理有限公司", "desc": ""},
    "文周投资": {"name": "上海文周投资管理有限公司", "desc": ""},
    "贞吉资本": {"name": "深圳市贞吉资本私募股权投资管理有限公司", "desc": ""},
    "联东投资": {"name": "北京联东投资（集团）有限公司", "desc": ""},
    "百丽国际": {"name": "百麗國際控股有限公司", "desc": ""},
    "开云集团": {"name": "開雲集團有限公司", "desc": ""},
    "Horizons Ventures维港投资": {"name": "Horizons Ventures维港投资", "desc": "Horizons Ventures（维港投资）成立于1999年，是一家重点关注能够引领行业变革的技术创新性公司的投资机构，李嘉诚旗下投资基金。  "},
    "合肥创投": {"name": "合肥市创新科技风险投资有限公司", "desc": ""},
    "临港智兆": {"name": "上海临创投资管理有限公司", "desc": ""},
    "赛天资本": {"name": "上海赛天投资管理有限公司", "desc": ""},
    "WaveFront Ventures创想未来资本": {"name": "平潭综合实验区创想未来投资合伙企业（有限合伙）", "desc": ""},
    "华泰新产业基金": {"name": "深圳市华泰瑞麟股权投资基金合伙企业（有限合伙）", "desc": ""},
    "华山资本WestSummit Capital": {"name": "华山资本", "desc": "华山资本是一只全球化成长期的风险投资基金，投资中国与海外的高科技公司并为被投公司带来深度的价值创造。华山资本的核心投资团队来自拥有多年企业运营经验的成功企业家、纳斯达克上市公司CEO及高管。"},
    "中通集团": {"name": "中通集團有限公司", "desc": ""},
    "新东方产业基金": {"name": "宁波梅山保税港区朗征投资管理合伙企业（有限合伙）", "desc": ""},
    "厦门建发新兴投资": {"name": "厦门建发新兴产业股权投资有限责任公司", "desc": ""},
    "Amadeus Capital Partners": {"name": "Amadeus Capital", "desc": "Amadeus Capital是一家全球性的技术投资者，投资于从种子到风险收购的所有阶段的技术公司；"},
    "新浪资本": {"name": "新浪資本有限公司", "desc": ""},
    "杭州源琛": {"name": "杭州源琛股权投资合伙企业（有限合伙）", "desc": ""},
    "厚德前海": {"name": "深圳市厚德前海基金管理有限公司", "desc": ""},
    "清源资本": {"name": "清源资本管理（广州）有限公司", "desc": ""},
    "春涧资本": {"name": "深圳市春涧商业服务有限公司", "desc": ""},
    "唐彬森": {"name": "x", "desc": ""},
    "阳光创投": {"name": "贵州阳光创投电子商务有限公司", "desc": ""},
    "360集团": {"name": "奇酷互联网络科技（深圳）有限公司", "desc": ""},
    "腾讯产业生态": {"name": "x", "desc": ""},
    "产业投资人": {"name": "x", "desc": ""},
    "王岑创立的": {"name": "x", "desc": ""},
    "经纬资本": {"name": "xxx", "desc": ""},
    "博信基金": {"name": "博信股权投资基金管理股份有限公司", "desc": ""},
    "英特尔投资Intel Capital": {"name": "Intel Capital", "desc": "英特尔投资是英特尔公司下设的事业部门，在全球范围内向创新型科技公司进行资本投资。"},
    "创业接力": {"name": "上海创业接力科技金融集团有限公司", "desc": ""},
    "梅赛德斯-奔驰": {"name": "戴姆勒-奔驰汽车公司", "desc": "梅赛德斯-奔驰（Mercedes-Benz）是戴姆勒-奔驰汽车公司旗下一个世界闻名的豪华汽车品牌。"},
    "曾鸣": {"name": "x", "desc": ""},
    "云栖创投": {"name": "杭州云栖创投股权投资合伙企业（有限合伙）", "desc": ""},
    "MFund魔量基金": {"name": "MFund魔量资本", "desc": "MFund魔量基金成立于2015年，是一家新成立的移动互联网早期投资基金，前身是网龙与IDG资本共同设立的mFund移动互联网投资基金。"},
    "深圳市引导基金": {"name": "深圳市引导基金投资有限公司", "desc": ""},
    "麓谷高新创投": {"name": "长沙麓谷高新移动互联网创业投资有限公司", "desc": ""},
    "36氪基金": {"name": "溫氏國際集團有限公司", "desc": ""},
    "DSG Consumer Partners": {"name": "DSG Consumer Partners", "desc": "DSG Consumer Partners（“DSGCP”）是一家专注于识别，选择和投资消费者业务的投资公司。DSGCP将主要在非上市公司中持有少数股权，但将考虑与合适的管理团队进行控制交易。  "},
    "苏高新": {"name": "x", "desc": ""},
    "北京集成电路尖端芯片基金": {"name": "北京集成电路尖端芯片股权投资中心（有限合伙）", "desc": ""},
    "中金启辰基金": {"name": "中金启辰（苏州）新兴产业股权投资基金合伙企业（有限合伙）", "desc": ""},
    "中集产业基金": {"name": "中集集团产业基金", "desc": ""},
    "李星星": {"name": "x", "desc": ""},
    "华岩资本ChinaRock": {"name": "華岩（資本）有限公司", "desc": ""},
    "某著名美元基金": {"name": "x", "desc": ""},
    "上海国资投资平台": {"name": "溫氏國際集團有限公司", "desc": ""},
    "4DX Ventures": {"name": "溫氏國際集團有限公司", "desc": ""},
    "eWTP基金": {"name": "溫氏國際集團有限公司", "desc": ""},
    "英飞尼迪Infinity": {"name": "英飞尼迪集团（Infinity Group）", "desc": ""},
    "中经合集团": {"name": "中经合集团", "desc": "中经合集团成立于1993年，是一家专注于早期和扩张期企业的风险投资公司。管理逾7.5亿美元的基金，已投资近百家企业。  "},
    "西湖科创投": {"name": "杭州西湖区科创股权投资有限公司", "desc": ""},
    "国开母基金": {"name": "上海国方私募基金管理有限公司", "desc": ""},
    "虎童基金": {"name": "虎童股权投资基金管理（天津）有限公司", "desc": ""},
    "创世伙伴CCV": {"name": "宁波创世基石投资管理有限公司", "desc": ""},
    "服贸基金": {"name": "服务贸易创新发展引导基金（有限合伙）", "desc": ""},
    "原有股东": {"name": "x", "desc": ""},
    "成为创伴": {"name": "上海成为创伴创业投资合伙企业（有限合伙）", "desc": ""},
    "众合瑞民": {"name": "深圳市众合瑞民产学研投资管理有限公司", "desc": ""},
    "苏州隆门创投": {"name": "苏州隆门创业投资合伙企业（有限合伙）", "desc": ""},
    "Horizons Ventures维港": {"name": "Horizons Ventures（维港投资）", "desc": "Horizons Ventures（维港投资）成立于1999年，是一家重点关注能够引领行业变革的技术创新性公司的投资机构，李嘉诚旗下投资基金。  "},
    "MindWorks Capital概念资本": {"name": "MindWorks Capital", "desc": "MindWorks 是一家泛亚风险投资公司，成立于 2013 年，在香港、北京和雅加达设有办事处。  "},
    "新丝路金控": {"name": "新丝路金控投资管理有限公司", "desc": ""},
    "春泥资本": {"name": "杭州春泥企业管理咨询合伙企业（有限合伙）", "desc": ""},
    "合肥市政府": {"name": "x", "desc": ""},
    "江苏瑞华": {"name": "江苏瑞华投资控股集团有限公司", "desc": ""},
    "中金锋泰基金": {"name": "杭州中金锋泰股权投资合伙企业（有限合伙）", "desc": ""},
    "LB Investment": {"name": "LB Investment", "desc": "LB Investment，原LG风险投资，是韩国最大的风险投资机构，设立了23个基金，投资了300余家企业，大多数是IT领域的处于早期至扩张期的公司。 "},
    "百世集团": {"name": "百世物流科技（中国）有限公司", "desc": ""},
    "优多资本": {"name": "unknow", "desc": ""},
    "普恩国新": {"name": "石家庄高新区普恩国新股权投资中心（有限合伙）", "desc": ""},
    "Summit Partners": {"name": "Summit Partners", "desc": "Summit Partners 成立于1984年，是一家私募股权机构，主要投资于成长期。  "},
    "元和科创": {"name": "北京元和科创股权投资管理中心（有限合伙）", "desc": ""},
    "苏州清研资本": {"name": "苏州清研资本管理企业（有限合伙）", "desc": ""},
    "大湾区基金": {"name": "溫氏國際集團有限公司", "desc": ""},
    "Better Capital": {"name": "Better Capital", "desc": "Better Capital为Better Capital Funds的普通合伙人提供咨询服务。"},
    "Boehringer Ingelheim Venture Fund": {"name": "Boehringer Ingelheim Venture Fund", "desc": "Boehringer Ingelheim Venture Fund计划投资开创性的治疗方法和技术，这些方法和技术有可能促进患者护理并满足未满足的医疗需求。  "},
    "北京鸿瀚": {"name": "北京鸿瀚投资基金管理中心（有限合伙）", "desc": ""},
    "苏州藤信": {"name": "苏州藤信创业投资合伙企业（有限合伙）", "desc": ""},
    "阿里系": {"name": "x", "desc": ""},
    "Qatar Investment Authority": {"name": "Qatar Investment Authority", "desc": "QIA由卡塔尔国于2005年成立，旨在通过多元化新资产类别来加强该国的经济。"},
    "蓝海资本BOCG": {"name": "深圳蓝海创业投资基金管理有限公司", "desc": ""},
    "兰馨亚洲投资集团": {"name": "兰馨投资咨询（上海）有限公司", "desc": ""},
    "盛趣资本": {"name": "盛趣私募基金管理（上海）有限公司", "desc": ""},
    "Franklin Templeton Investments": {"name": "Franklin Templeton Investments", "desc": ""},
    "头头是道加注": {"name": "x", "desc": ""},
    "深圳市罗湖引导基金": {"name": "深圳市罗湖引导基金投资有限公司", "desc": ""},
    "某全球美元投资集团": {"name": "x", "desc": ""},
    "中鑫创新": {"name": "苏州中鑫创新投资管理有限公司", "desc": ""},
    "合肥市": {"name": "x", "desc": ""},
    "软银愿景基金一期": {"name": "软银科技有限公司", "desc": ""},
    "襄禾": {"name": "襄禾商务咨询（北京）有限公司", "desc": ""},
    "东科创星": {"name": "武汉东科创星管理咨询有限公司", "desc": ""},
    "SignalFire": {"name": "SignalFire", "desc": "SignalFire是一家风险投资公司，投资于种子阶段公司和分拆公司。"},
    "Silver Lake": {"name": "Silver Lake Partners", "desc": "Silver Lake Partners（银湖投资）成立于1999年，是一家全球性的私人投资公司，目前管理超过140亿美元的资产。"},
    "TPG亚洲基金": {"name": "TPG亚洲资本", "desc": "TPG亚洲资本是首批在亚洲投资的私募股权投资机构，深耕中国、印度、东南亚地区、日本、韩国和澳大利亚等市场。"},
    "熵一贯喜": {"name": "湖南熵一贯喜资产管理有限公司", "desc": ""},
    "兴杭国投": {"name": "闽西兴杭国有资产投资经营有限公司", "desc": ""},
    "梅花天使": {"name": "x", "desc": ""},
    "凯辉汽车基金": {"name": "湖北凯辉股权投资管理有限公司", "desc": ""},
    "CBC宽带资本": {"name": "北京天地融创创业投资有限公司", "desc": ""},
    "智友金苗": {"name": "宁波梅山保税港区智友金苗投资合伙企业（有限合伙）", "desc": ""},
    "Genuine": {"name": "x", "desc": ""},
    "北京信润恒": {"name": "北京信润恒股权投资合伙企业（有限合伙）", "desc": ""},
    "君联景铄": {"name": "珠海君联景铄股权投资合伙企业（有限合伙）", "desc": ""},
    "鼎晖新嘉": {"name": "深圳鼎晖新嘉股权投资基金合伙企业（有限合伙）", "desc": ""},
    "CPE战略": {"name": "x", "desc": ""},
    "真格教育基金": {"name": "嘉兴真格致知投资管理有限公司", "desc": ""},
    "硅谷银行Silicon Valley Bank": {"name": "Silicon Valley Bank", "desc": "Silicon Valley Bank 成立于1983年10月，主要致力于技术、生命科学、清洁技术、风险投资、私募股权等业务，提供行业知识、洽谈，融资、财资管理，企业投资及国际银行服务，其客户通过全球27美国办事处和七个国际业务展开。"},
    "万科集团": {"name": "万科企业股份有限公司", "desc": ""},
    "光谷人才基金": {"name": "武汉光谷人才私募投资管理有限公司", "desc": ""},
    "北京电商投资": {"name": "x", "desc": ""},
    "夏尔巴资本": {"name": "珠海夏尔巴股权投资管理有限公司", "desc": ""},
    "济南先投股权": {"name": "济南先投股权投资管理有限公司", "desc": ""},
    "光大控股新经济": {"name": "中國光大控股有限公司", "desc": ""},
    "idg资本": {"name": "IDG Ventures", "desc": "IDG Ventures （海外）是一家风险投资公司，主要投资领域为新媒体、消费者网络和企业IT等。  "},
    "北京泰康投资": {"name": "北京泰康投资管理有限公司", "desc": ""},
    "渠成愿达": {"name": "深圳渠成愿达投资合伙企业（有限合伙）", "desc": ""},
    "晨道资本": {"name": "宁波梅山保税港区晨道投资合伙企业（有限合伙）", "desc": ""},
    "碧鸿投资": {"name": "宁波梅山保税港区碧鸿投资管理有限公司", "desc": ""},
    "中缔资本": {"name": "上海中缔投资有限公司", "desc": ""},
    "智铭资本": {"name": "共青城东兴智铭投资管理合伙企业（有限合伙）", "desc": ""},
    "平潭创想未来": {"name": "平潭综合实验区创想未来投资合伙企业（有限合伙）", "desc": ""},
    "物源资本": {"name": "物源（宁夏）股权投资合伙企业（有限合伙）", "desc": ""},
    "贝塔斯曼亚洲投资基金": {"name": "贝塔斯曼股权投资基金管理（上海）有限公司", "desc": ""},
    "东莞金控": {"name": "东莞金融控股集团有限公司", "desc": ""},
    "WaterBridge Ventures": {"name": "WaterBridge Ventures", "desc": "印度科技企业创业的风险催化剂。Venture Catalyst for Tech Enterpreneurship in India.  "},
    "何小鹏": {"name": "x", "desc": ""},
    "九毛九集团": {"name": "广州九毛九餐饮连锁有限公司", "desc": ""},
    "拉芳品观华熙投资基金": {"name": "珠海拉芳品观华熙投资基金合伙企业（有限合伙）", "desc": ""},
    "锐合投资": {"name": "上海锐合股权投资管理有限公司", "desc": ""},
    "海通创新资本": {"name": "海通创新私募基金管理有限公司", "desc": ""},
    "上海联和投资": {"name": "上海联和投资有限公司", "desc": ""},
    "贝霖资本": {"name": "海南贝霖泓泽企业管理合伙企业（有限合伙）", "desc": ""},
    "璞瑞投资基金": {"name": "璞瑞投资有限公司", "desc": ""},
    "西交一八九六资本": {"name": "西安西交一八九六资本管理有限公司", "desc": ""},
    "深圳厚德前海基金": {"name": "深圳市厚德前海基金管理有限公司", "desc": ""},
    "米哈游miHoYo": {"name": "上海米哈游网络科技股份有限公司", "desc": ""},
    "梅花新势能基金": {"name": "x", "desc": ""},
    "北京文投": {"name": "北京市文化投资发展集团有限责任公司", "desc": ""},
    "广州开发区基金": {"name": "广州开发区产业基金投资集团有限公司", "desc": ""},
    "厚朴资本": {"name": "厚朴投资管理有限责任公司", "desc": ""},
    "百榕资本": {"name": "北京百榕管理咨询有限公司", "desc": ""},
    "昕先投资": {"name": "上海昕先股权投资基金管理有限公司", "desc": ""},
    "海高集团": {"name": "浙江海高控股集团有限公司", "desc": ""},
    "和玉资本（MSA Capital）": {"name": "和玉股权投资基金管理（天津）有限公司", "desc": ""},
    "某行业资源方": {"name": "x", "desc": ""},
    "格物资本": {"name": "北京格物致和管理咨询有限公司", "desc": ""},
    "High Alpha": {"name": "High Alpha", "desc": "High Alpha是一家风险投资公司。  "},
    "银河源汇": {"name": "银河源汇投资有限公司", "desc": ""},
    "KTB投资集团": {"name": "开铂银科（成都）创业投资企业", "desc": ""},
    "New Enterprise Associates": {"name": "New Enterprise Associates, Inc. ", "desc": "New Enterprise Associates, Inc. is a global venture capital firm focused on helping entrepreneurs build transformational businesses across multiple stages, sectors, and geographies. With over $19 billion in cumulative committed capital since the firm’s founding in 1977, NEA invests in technology and healthcare companies at all stages in a company’s"},
    "长禾资本": {"name": "深圳长禾资本管理有限公司", "desc": ""},
    "产业方": {"name": "x", "desc": ""},
    "新瞳资本": {"name": "上海新瞳博达私募基金管理有限公司", "desc": ""},
    "纪源": {"name": "x", "desc": ""},
    "中润资本": {"name": "中润资本管理有限公司", "desc": ""},
    "个人天使投资人": {"name": "x", "desc": ""},
    "春华创投": {"name": "春华投资有限公司", "desc": ""},
    "保碧基金": {"name": "保利碧桂园产业链赋能基金", "desc": ""},
    "杭州微尘创业服务合伙企业": {"name": "杭州微尘创业服务合伙企业（有限合伙）", "desc": ""},
    "Gokul Rajaram": {"name": "x", "desc": ""},
    "华和生鲜": {"name": "武汉华和农业发展有限公司", "desc": ""},
    "新天资本": {"name": "无锡新天资本有限公司", "desc": ""},
    "CMC创投": {"name": "CMC Capital", "desc": "CMC资本(CMC Capital)由黎瑞刚先生于2010年创立并担任创始合伙人，是一家专注于科技、消费、文娱领域的专业投资机构，先后在上海、北京、香港设立办公室。目前，CMC资本旗下管理三支美元和两支人民币基金，管理资产总额超过300亿人民币。"},
    "峰瑞": {"name": "上海自友投资管理有限公司", "desc": ""},
    "Redpoint Ventures红点全球基金": {"name": "Redpoint Ventures", "desc": "红点创投创建于1999年 [1]  ，是一家源自硅谷的风险投资基金 [2]  ，2005年在中国设立办公室 [3]  ，2016年设立中国基金 [4]  ，由红点中国团队独立运营 [4]  。"},
    "中央企业贫困地区产业投资基金": {"name": "中央企业乡村产业投资基金股份有限公司", "desc": ""},
    "Ascent": {"name": "x", "desc": ""},
    "Trifecta": {"name": "Trifecta", "desc": "Trifecta是全美最大的有机膳食外卖服务平台，也是iPhone健康类全球排名前30的Trifecta应用的开发者。"},
    "Vertex": {"name": "Vertex-Global Holding B.V.", "desc": "Vertex-Global Holding B.V.是一家位于荷兰的牙科3D打印材料公司。  "},
    "王道资本": {"name": "杭州王道创业投资管理有限公司", "desc": ""},
    "国际物流华运国际集团": {"name": "深圳市华运国际物流有限公司", "desc": ""},
    "深圳国资": {"name": "深圳国资协同发展私募基金合伙企业（有限合伙）", "desc": ""},
    "华住酒店集团": {"name": "华住酒店管理有限公司", "desc": ""},
    "中赢资本": {"name": "浙江中赢资本投资合伙企业（有限合伙）", "desc": ""},
    "友邦投资": {"name": "抚州市友邦科技中心（普通合伙）", "desc": ""},
    "老虎全球管理基金": {"name": "TigerGlobal Management", "desc": ""},
    "Tiger老虎基金(中国)": {"name": "老虎亚洲基金（Tiger Global Mauritius Fund）", "desc": "老虎亚洲基金（Tiger Global Mauritius Fund）是一家全球的风险投资机构，本站主要关注老虎基金在中国的投资情况。"},
    "凯思博": {"name": "北京凯思博投资管理有限公司", "desc": ""},
    "Vostok New Ventures": {"name": "Vostok New Venture", "desc": "Vostok New Venture是一家瑞典投资公司，为在线市场的公司提供资金。"},
    "42 Capital-42章经": {"name": "北京四十二章经科技有限公司", "desc": ""},
    "Sprout Venture Partners": {"name": "Sprout Venture Partners Fund", "desc": "Sprout Venture Partners Fund是SEBI注册的I类另类投资基金。它的创建是为了使印度活跃的天使投资市场制度化，并得到了著名的第一代和第二代企业家的支持。"},
    "平安创新投资基金": {"name": "深圳市平安创新资本投资有限公司", "desc": ""},
    "领衔健康基金": {"name": "宁波领衔企业管理咨询有限公司", "desc": ""},
    "青岛全球财富中心": {"name": "青岛全球财富中心开发建设有限公司", "desc": ""},
    "瀚漾投资": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},
    "": {"name": "溫氏國際集團有限公司", "desc": ""},


}
keyword = "快手所属公司"
url = "https://www.baidu.com/s?wd={}".format(quote(keyword))
# print(url)
# r = requests.get(url, headers=HEADER)
# print(r.content)